import { useListNotifications, useMarkNotificationRead } from "@workspace/api-client-react";
import { getListNotificationsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Bell, Check, CheckCircle2, ExternalLink, Loader2, RefreshCw } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

function isUrgent(notification: { message: string; detail?: string | null }) {
  const text = `${notification.message} ${notification.detail ?? ""}`.toLowerCase();
  return [
    "emergency",
    "priority",
    "elevator down",
    "elevator is down",
    "new resident report",
    "resident report",
  ].some((term) => text.includes(term));
}

export default function Notifications() {
  const queryClient = useQueryClient();
  const {
    data: notifications,
    isLoading,
    isError,
    error,
    refetch,
    isFetching,
  } = useListNotifications({
    query: {
      // Notifications can be generated by another staff member or a device.
      queryKey: getListNotificationsQueryKey(),
      refetchInterval: 30_000,
      staleTime: 15_000,
      refetchOnMount: "always",
    },
  });
  const markRead = useMarkNotificationRead();
  const items = notifications ?? [];
  const unread = items.filter((notification) => !notification.read);

  const invalidateNotifications = () =>
    queryClient.invalidateQueries({ queryKey: getListNotificationsQueryKey() });

  const handleMarkRead = async (id: string) => {
    await markRead.mutateAsync({ id });
    await invalidateNotifications();
  };

  const handleMarkAllRead = async () => {
    // There is no separate bulk endpoint in the generated client. Use the
    // supported per-notification operation so this remains server-backed.
    await Promise.all(unread.map(({ id }) => markRead.mutateAsync({ id })));
    await invalidateNotifications();
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Notifications</h1>
          <p className="text-muted-foreground text-sm">View and manage your alerts.</p>
        </div>
        {unread.length > 0 && (
          <Button
            variant="outline"
            size="sm"
            className="gap-2 self-start sm:self-auto"
            onClick={handleMarkAllRead}
            disabled={markRead.isPending}
          >
            {markRead.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
            Mark all read
          </Button>
        )}
      </div>

      {markRead.isError && (
        <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">
          We couldn&apos;t update that notification. Please try again.
        </div>
      )}

      <div className="bg-card rounded-[14px] shadow-sm border border-border">
        <div className="p-4">
          {isLoading ? (
            <div className="p-12 text-center text-muted-foreground" role="status">
              <Loader2 className="w-6 h-6 animate-spin mx-auto mb-3" />
              Loading notifications...
            </div>
          ) : isError ? (
            <div className="p-12 text-center" role="alert">
              <Bell className="w-12 h-12 text-destructive/40 mx-auto mb-4" />
              <h3 className="text-lg font-bold">Notifications are unavailable</h3>
              <p className="text-sm text-muted-foreground mt-1">
                {error instanceof Error ? error.message : "We couldn't load your alerts right now."}
              </p>
              <Button variant="outline" size="sm" className="mt-4 gap-2" onClick={() => refetch()}>
                <RefreshCw className="w-4 h-4" /> Try again
              </Button>
            </div>
          ) : items.length === 0 ? (
            <div className="p-12 text-center flex flex-col items-center">
              <Bell className="w-12 h-12 text-muted-foreground/30 mb-4" />
              <h3 className="text-lg font-bold">All caught up!</h3>
              <p className="text-sm text-muted-foreground mt-1">You have no notifications.</p>
            </div>
          ) : (
            <div className="divide-y divide-border">
              {items.map((notification) => {
                const urgent = isUrgent(notification);
                const pendingEmployee = notification.message === "Employee pending approval";
                const content = (
                  <>
                    <div
                      className={`w-10 h-10 rounded-full shrink-0 grid place-items-center ${
                        urgent
                          ? "bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-300"
                          : notification.read
                            ? "bg-secondary text-muted-foreground"
                            : "bg-primary text-sidebar"
                      }`}
                    >
                      <Bell className="w-5 h-5" />
                    </div>
                    <div className="flex-1 min-w-0 pt-0.5">
                      <p className={`text-[14.5px] ${notification.read ? "" : "font-semibold"} ${urgent ? "text-red-700 dark:text-red-300" : ""}`}>
                        {notification.message}
                      </p>
                      {notification.detail && (
                        <p className={`text-sm mt-1 line-clamp-2 ${urgent ? "text-red-700/80 dark:text-red-300/80" : "text-muted-foreground"}`}>
                          {notification.detail}
                        </p>
                      )}
                      <span className="text-xs text-muted-foreground block mt-2">
                        {new Date(notification.at).toLocaleString()}
                      </span>
                    </div>
                  </>
                );

                return (
                  <div
                    key={notification.id}
                    className={`flex items-start gap-4 p-4 transition-colors ${
                      urgent
                        ? "border-l-4 border-l-red-500 bg-red-50/70 dark:bg-red-950/20"
                        : notification.read
                          ? "opacity-60"
                          : "bg-primary/5"
                    }`}
                  >
                    {notification.reportId ? (
                      <Link
                        href={pendingEmployee ? `/team?staffId=${encodeURIComponent(notification.reportId)}` : "/reports"}
                        className="flex min-w-0 flex-1 items-start gap-4 rounded-md outline-none focus-visible:ring-2 focus-visible:ring-ring"
                        onClick={() => {
                          if (!notification.read && !pendingEmployee) void handleMarkRead(notification.id);
                        }}
                      >
                        {content}
                        <ExternalLink className="w-4 h-4 shrink-0 mt-1 text-muted-foreground" aria-label="View report" />
                      </Link>
                    ) : (
                      <div className="flex min-w-0 flex-1 items-start gap-4">{content}</div>
                    )}
                    {!notification.read && !pendingEmployee && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="shrink-0 gap-1.5 h-8 text-xs font-semibold"
                        onClick={() => void handleMarkRead(notification.id)}
                        disabled={markRead.isPending}
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        Mark read
                      </Button>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
        {!isLoading && !isError && items.length > 0 && (
          <div className="border-t border-border px-4 py-3 text-xs text-muted-foreground flex items-center justify-between">
            <span>{unread.length ? `${unread.length} unread` : "All notifications read"}</span>
            <span className="flex items-center gap-1.5">
              {isFetching && <Loader2 className="w-3 h-3 animate-spin" />}
              Updates automatically
            </span>
          </div>
        )}
      </div>
    </div>
  );
}