export const LM_DEVELOPMENT_NAMES = [
  "20 Littleton",
  "50 & 55 South Essex Avenue",
  "Alafia",
  "Arverne East – Phase 1 + 2",
  "Arverne East – Phase 3",
  "Arverne View",
  "Beach Green Dunes II",
  "Bronx Point",
  "Coney Island",
  "Cross Bronx Preservation (Baychester & Murphy)",
  "El Rancho Verde",
  "Essex Crossing",
  "Hahne & Co.",
  "Jackie Robinson + Harlem Scattered Sites",
  "Jasper",
  "Kingsbridge Heights Apartments",
  "Lincoln Correctional Facility Redevelopment",
  "Linwood Park Apartments",
  "Marcus Garvey Apartments",
  "Marcus Garvey Extension Phase 1 (Sites B/D + Site F)",
  "Miramar",
  "National Black Theatre Redevelopment",
  "National Urban League",
  "Navy Green",
  "Newark Urby",
  "Norman Towers",
  "River Commons",
  "Sendero Verde",
  "St. Barnabas",
  "Stanley Avenue Preservation",
  "Stella",
  "Story Avenue East & West",
  "The Carolina",
  "The Crossing",
  "The Heritage",
  "The Miles",
  "The Niko East Village",
  "The Parker",
  "The Pearson Court Square",
  "The Rollins",
  "Triborough Portfolio",
  "Walker House",
  "Williamsbridge Gardens",
  "Zion Towers",
] as const;