export const NYCHA_DEVELOPMENT_NAMES = [
  "Adams",
  "Albany",
  "Albany II",
  "Amsterdam",
  "Amsterdam Addition",
  "Astoria",
  "Atlantic Terminal Site 4B",
  "Bailey Avenue–West 193rd Street",
  "Baisley Park",
  "Baruch",
  "Baruch Houses Addition",
  "Bay View",
  "Beach 41st Street–Beach Channel Drive",
  "Berry",
  "Bland",
  "Borinquen Plaza I",
  "Borinquen Plaza II",
  "Boston Road Plaza",
  "Boston Secor",
  "Boynton Avenue Rehab",
  "Bracetti Plaza",
  "Breukelen",
  "Brevoort",
  "Bronx River",
  "Bronx River Addition",
  "Brown",
  "Brownsville",
  "Bryant Avenue–East 174th Street",
  "Bushwick",
  "Butler",
  "Campos Plaza II",
  "Carey Gardens",
  "Carleton Manor",
  "Carver",
  "Cassidy–Lafayette",
  "Castle Hill",
  "Chelsea",
  "Claremont Parkway–Franklin Avenue",
  "Claremont Rehab (Group 2)",
  "Claremont Rehab (Group 3)",
  "Claremont Rehab (Group 4)",
  "Claremont Rehab (Group 5)",
  "Clason Point Gardens",
  "Clinton",
  "College Avenue–East 165th Street",
  "Coney Island",
  "Coney Island I (Site 1B)",
  "Coney Island I (Site 8)",
  "Coney Island I (Sites 4 & 5)",
  "Conlon Lihfe Tower",
  "Cooper Park",
  "Corsi Houses",
  "Cypress Hills",
  "Davidson",
  "De Hostos Apartments",
  "Douglass Addition",
  "Douglass I",
  "Douglass II",
  "Drew–Hamilton",
  "Dyckman",
  "Eagle Avenue–East 163rd Street",
  "East 152nd Street–Courtlandt Avenue",
  "East 165th Street–Bryant Avenue",
  "East 180th Street–Monterey Avenue",
  "East New York City Line",
  "East River",
  "Eastchester Gardens",
  "Elliott",
  "Farragut",
  "First Houses",
  "Forest",
  "Fulton",
  "Garvey (Group A)",
  "Glebe Avenue–Westchester Avenue",
  "Glenmore Plaza",
  "Glenwood",
  "Gompers",
  "Gowanus",
  "Grant",
  "Gravesend",
  "Gun Hill",
  "Haber",
  "Hammel",
  "Harborview Terrace",
  "Harrison Avenue Rehab (Group A)",
  "Harrison Avenue Rehab (Group B)",
  "Hernandez",
  "Highbridge Gardens",
  "Holmes Towers",
  "Howard",
  "Howard Avenue–Park Place",
  "Hughes Apartments",
  "Hunts Point Avenue Rehab",
  "Hylan",
  "Ingersoll",
  "International Tower",
  "Isaacs",
  "Jackson",
  "Jefferson",
  "Johnson",
  "King Towers",
  "Kingsborough",
  "Kingsborough Extension",
  "LaGuardia",
  "LaGuardia Addition",
  "Lafayette",
  "Latimer Gardens",
  "Leavitt Street–34th Avenue",
  "Lehman Village",
  "Lexington",
  "Lincoln",
  "Long Island Baptist Houses",
  "Longfellow Avenue Rehab",
  "Low Houses",
  "Manhattanville",
  "Marcy",
  "Melrose",
  "Metro North Plaza",
  "Middletown Plaza",
  "Mitchell",
  "Morris Park Senior Citizens Home",
  "Morrisania Air Rights",
  "Mott Haven",
  "Ocean Bay (Bayside)",
  "Ocean Bay (Oceanside)",
  "Ocean Hill Apartments",
  "Ocean Hill–Brownsville",
  "Park Rock Rehab",
  "Patterson",
  "Polo Grounds Towers",
  "Pomonok",
  "P.S.A. Rehab (various)",
  "Queensbridge North",
  "Queensbridge South",
  "Ravenswood",
  "Red Hook East",
  "Red Hook West",
  "Rehab Program (Taft Rehabs)",
  "Richmond Terrace",
  "Riis",
  "Robinson",
  "Rutland Towers",
  "Sack Wern",
  "Samuel (City)",
  "Saratoga Village",
  "Sheepshead Bay",
  "Smith",
  "Soundview",
  "South Jamaica",
  "St. Nicholas",
  "Stapleton",
  "Sterling Place Rehabs (Saint Johns–Sterling)",
  "Sterling Place Rehabs (Saint Johns–Buffalo)",
  "Stuyvesant Gardens I",
  "Stuyvesant Gardens II",
  "Sumner",
  "Sutter Avenue–Union Street",
  "Taft",
  "Tapscott Street Rehab",
  "Tompkins",
  "Twin Parks East (Site 9)",
  "Twin Parks (other sites)",
  "UPACA (Site 5)",
  "UPACA (Site 6)",
  "University Avenue Rehab",
  "Van Dyke",
  "Van Dyke II",
  "Vladeck",
  "Vladeck II",
  "Wagner",
  "Walt Whitman",
  "Washington Avenue (1162–1176)",
  "Watson Avenue (1471)",
  "West Brighton I",
  "West Brighton II",
  "West Side Urban Renewal",
  "Williamsburg",
  "Woodside",
] as const;